version: '3.8'
services:
  front:
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    volumes:
      # ローカルにバインドマウントしたくない場合
      - /app/node_modules
      # ローカルにバインドマウントしたい場合
      # - ./app/node_modules:/app/node_modules
      - ./app:/app

  npm:
    build:
      context: ./app
      dockerfile: Dockerfile
    working_dir: /app
    entrypoint: ['npm']
    volumes:
      - ./app:/app
      # ローカルにバインドマウントしたくない場合
      - /app/node_modules
      # ローカルにバインドマウントしたい場合
      # - ./app/node_modules:/app/node_modules

  # create-react-app with typecript
  create-react-app:
    image: node:16
    working_dir: /app
    command: npx create-react-app my-app
    volumes:
      - ./app:/app
      # ローカルにバインドマウントしたくない場合
      - /app/node_modules
      # ローカルにバインドマウントしたい場合
      # - ./app/node_modules:/app/node_modules
