version: '3.8'
services:
  front:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./app:/app

  npm:
    image: node:16
    entrypoint: ['npm']
    volumes:
      - ./app:/app
